export const ROUTES = {
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',

  dashboard: '/dashboard',
  agentActivity: '/agent-activity',
  timeline: '/timeline',
  commandCenter: '/command-center',
  dealPerformance: '/deal-performance',
  myCustomerActivity: '/my-customer-activity',
  businessKnowledge: '/business-knowledge',
  emailIntelligence: '/ai-email-inbox',
  finance: '/finance',
  todoEod: '/todo-eod',
  chat: '/chat',
  chatConversation: (id: string) => `/chat/${id}`,
  integrations: '/integrations',
  notifications: '/notifications',

  settings: '/settings',
  settingsGeneral: '/settings/general',
  settingsNotifications: '/settings/notifications',
  settingsSecurity: '/settings/security',
  settingsAgentRoles: '/settings/agent-roles',
  settingsUsers: '/settings/users',
  settingsSalesTargets: '/settings/sales-targets',
  settingsDealAssignment: '/settings/deal-assignment',
  settingsWorkflows: '/settings/workflows',

  profile: '/profile',
} as const;
